server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Proxy de la API al backend Django
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy de archivos media (PDFs generados)
    location /media/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
    }

    # React Router — todas las rutas van al index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
