# Generated by Django 5.1.4 on 2026-07-24 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("nit", models.CharField(blank=True, max_length=40, null=True)),
                ("telefono", models.CharField(blank=True, max_length=30, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("direccion", models.CharField(blank=True, max_length=300, null=True)),
                ("vinculado", models.BooleanField(default=False)),
                (
                    "documento_vinculacion_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "clientes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Cotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=50, unique=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente_aprobacion", "Pendiente de aprobación"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="pendiente_aprobacion",
                        max_length=25,
                    ),
                ),
                ("fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
                ("motivo_rechazo", models.TextField(blank=True, null=True)),
                ("notas", models.TextField(blank=True, null=True)),
                ("pdf_path", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "cotizaciones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Despacho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=50, unique=True)),
                ("fecha", models.DateField()),
                (
                    "recibido_por",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("cliente_retira", models.BooleanField(default=True)),
                (
                    "placa_vehiculo",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("notas", models.TextField(blank=True, null=True)),
                ("pdf_path", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "despachos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("triturado", "Triturado"),
                            ("agregado", "Agregado"),
                            ("otro", "Otro"),
                        ],
                        default="agregado",
                        max_length=20,
                    ),
                ),
                ("unidad_medida", models.CharField(default="m3", max_length=20)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "materiales",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Planta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, unique=True)),
                ("ubicacion", models.CharField(blank=True, max_length=250, null=True)),
                ("activa", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "plantas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("hashed_password", models.CharField(max_length=255)),
                ("nombre", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("comercial", "Comercial"),
                            ("aprobador", "Aprobador"),
                            ("financiera", "Financiera"),
                            ("planta", "Planta"),
                        ],
                        default="comercial",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("firma_path", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="DespachoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "despacho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.despacho",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.material"
                    ),
                ),
            ],
            options={
                "db_table": "despacho_items",
            },
        ),
        migrations.CreateModel(
            name="CotizacionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.cotizacion",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.material"
                    ),
                ),
            ],
            options={
                "db_table": "cotizacion_items",
            },
        ),
        migrations.CreateModel(
            name="OrdenSuministro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=50, unique=True)),
                ("notificada_planta", models.BooleanField(default=False)),
                ("fecha_notificacion", models.DateTimeField(blank=True, null=True)),
                ("notas", models.TextField(blank=True, null=True)),
                ("pdf_path", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cotizacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orden_suministro",
                        to="api.cotizacion",
                    ),
                ),
                (
                    "planta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes_suministro",
                        to="api.planta",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordenes_creadas",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "ordenes_suministro",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="despacho",
            name="orden_suministro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="despachos",
                to="api.ordensuministro",
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="planta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cotizaciones",
                to="api.planta",
            ),
        ),
        migrations.CreateModel(
            name="SolicitudCotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=50, unique=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("cotizada", "Cotizada"),
                            ("cerrada", "Cerrada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("notas", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes",
                        to="api.cliente",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_creadas",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "solicitudes_cotizacion",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="solicitud",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cotizacion",
                to="api.solicitudcotizacion",
            ),
        ),
        migrations.CreateModel(
            name="SolicitudCotizacionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.material"
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.solicitudcotizacion",
                    ),
                ),
            ],
            options={
                "db_table": "solicitud_cotizacion_items",
            },
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "comprobante_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
                ("motivo_rechazo", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cotizacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pago",
                        to="api.cotizacion",
                    ),
                ),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pagos_aprobados",
                        to="api.user",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pagos_creados",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "pagos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="despacho",
            name="creado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="despachos_creados",
                to="api.user",
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="aprobado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cotizaciones_aprobadas",
                to="api.user",
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="creado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cotizaciones_creadas",
                to="api.user",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="creado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientes_creados",
                to="api.user",
            ),
        ),
        migrations.CreateModel(
            name="MaterialPlanta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precios_planta",
                        to="api.material",
                    ),
                ),
                (
                    "planta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precios_material",
                        to="api.planta",
                    ),
                ),
            ],
            options={
                "db_table": "material_plantas",
                "unique_together": {("material", "planta")},
            },
        ),
    ]
