# Generated by Django 5.1.15 on 2026-09-11 03:18

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClienteToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        default=api.models._generar_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("etiqueta", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "expira_at",
                    models.DateTimeField(default=api.models._vencimiento_por_defecto),
                ),
                ("usado_at", models.DateTimeField(blank=True, null=True)),
                ("revocado", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tokens_vinculacion",
                        to="api.cliente",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tokens_cliente_creados",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "cliente_tokens",
                "ordering": ["-created_at"],
            },
        ),
    ]
