# Generated by Django 5.1.15 on 2026-09-11 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_clientetoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="solicitud",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cotizaciones",
                to="api.solicitudcotizacion",
            ),
        ),
        migrations.AlterField(
            model_name="pago",
            name="cotizacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pagos",
                to="api.cotizacion",
            ),
        ),
        migrations.AlterField(
            model_name="solicitudcotizacion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("cotizada", "Cotizada"),
                    ("en_seguimiento", "En seguimiento"),
                    ("cerrada", "Cerrada"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Seguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("nota", "Nota"),
                            ("cotizacion_rechazada", "Cotización rechazada"),
                            ("cotizacion_aprobada", "Cotización aprobada"),
                            ("pago_rechazado", "Pago rechazado"),
                            ("pago_aprobado", "Pago aprobado"),
                            ("cotizacion_nueva", "Nueva cotización"),
                        ],
                        default="nota",
                        max_length=30,
                    ),
                ),
                ("texto", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguimientos",
                        to="api.solicitudcotizacion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seguimientos",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "seguimientos",
                "ordering": ["-created_at"],
            },
        ),
    ]
