# Generated by Django 5.1.15 on 2026-09-11 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_cotizacion_solicitud_alter_pago_cotizacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacionitem",
            name="planta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cotizacion_items",
                to="api.planta",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="planta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cotizaciones",
                to="api.planta",
            ),
        ),
        migrations.AlterField(
            model_name="ordensuministro",
            name="cotizacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordenes_suministro",
                to="api.cotizacion",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ordensuministro",
            unique_together={("cotizacion", "planta")},
        ),
    ]
