# Generated by Django 5.1.15 on 2026-09-11 03:44

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_backfill_planta_en_items"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitudToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        default=api.models._generar_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("expira_at", models.DateTimeField(blank=True, null=True)),
                ("usos", models.PositiveIntegerField(default=0)),
                ("ultimo_uso_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens_solicitud",
                        to="api.cliente",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tokens_solicitud_creados",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "solicitud_tokens",
                "ordering": ["-created_at"],
            },
        ),
    ]
