# Generated by Django 5.1.15 on 2026-09-11 23:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_solicitudtoken"),
    ]

    operations = [
        migrations.RenameField(
            model_name="materialplanta",
            old_name="precio_unitario",
            new_name="precio_especial",
        ),
        migrations.AddField(
            model_name="cliente",
            name="tipo_precio",
            field=models.CharField(
                choices=[
                    ("especial", "Venta especial"),
                    ("detal", "Venta página / clientes detal"),
                ],
                default="especial",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="iva_porcentaje",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("19"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="tipo_precio",
            field=models.CharField(
                choices=[
                    ("especial", "Venta especial"),
                    ("detal", "Venta página / clientes detal"),
                ],
                default="especial",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="materialplanta",
            name="precio_detal",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
    ]
