# Generated by Django 5.1.15 on 2026-09-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_precios_dos_tarifas_e_iva"),
    ]

    operations = [
        migrations.AddField(
            model_name="despacho",
            name="consecutivo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ordensuministro",
            name="fecha_suministro",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ordensuministro",
            name="placas_cliente",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="ordensuministro",
            name="placas_empresa",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="solicitudcotizacion",
            name="obra",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="cargo",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="telefono",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
