# Generated by Django 5.1.15 on 2026-09-24 02:08

import django.db.models.deletion
from django.db import migrations, models


def origen_desde_tarifa(apps, schema_editor):
    """Las líneas viejas salieron de la tarifa de su cotización."""
    CotizacionItem = apps.get_model("api", "CotizacionItem")
    CotizacionItem.objects.filter(cotizacion__tipo_precio="detal").update(origen_precio="detal")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_desactivar_datos_de_ejemplo"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="notas_aclaratorias",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cotizacionitem",
            name="origen_precio",
            field=models.CharField(
                choices=[
                    ("especial", "Venta especial"),
                    ("detal", "Venta página / clientes detal"),
                    ("manual", "Precio escrito a mano"),
                ],
                default="especial",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CotizacionAjuste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("cargo", "Cargo"), ("descuento", "Descuento")],
                        max_length=20,
                    ),
                ),
                (
                    "modo",
                    models.CharField(
                        choices=[("monto", "Monto fijo"), ("porcentaje", "Porcentaje")],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.CharField(max_length=200)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=14)),
                ("aplica_iva", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ajustes",
                        to="api.cotizacion",
                    ),
                ),
            ],
            options={
                "db_table": "cotizacion_ajustes",
                "ordering": ["orden", "id"],
            },
        ),
        migrations.RunPython(origen_desde_tarifa, migrations.RunPython.noop),
    ]
