# Generated by Django 5.1.4 on 2026-09-24 13:44

import api.models
import django.db.models.deletion
from django.db import migrations, models


def permisos_desde_rol(apps, schema_editor):
    """Los usuarios existentes arrancan con los permisos que les daba su rol."""
    from api.permissions import PERMISOS_POR_ROL
    User = apps.get_model("api", "User")
    for u in User.objects.all():
        if not u.permisos:
            u.permisos = PERMISOS_POR_ROL.get(u.rol, [])
            u.save(update_fields=["permisos"])


def tokens_y_items_de_ordenes(apps, schema_editor):
    """Cada orden existente: su token público y sus ítems, que antes se leían
    de la cotización (toda la parte de su planta)."""
    import secrets
    OrdenSuministro = apps.get_model("api", "OrdenSuministro")
    OrdenSuministroItem = apps.get_model("api", "OrdenSuministroItem")
    for o in OrdenSuministro.objects.select_related("cotizacion"):
        o.token_publico = secrets.token_urlsafe(32)
        o.save(update_fields=["token_publico"])
        for ci in o.cotizacion.items.all():
            planta_id = ci.planta_id or o.cotizacion.planta_id
            if planta_id == o.planta_id:
                OrdenSuministroItem.objects.create(orden=o, cotizacion_item=ci, cantidad=ci.cantidad)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_superusuario_y_perfil"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ordensuministro",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="despacho",
            name="soporte_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="materialplanta",
            name="cantidad_disponible",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="materialplanta",
            name="disponibilidad",
            field=models.CharField(
                choices=[
                    ("disponible", "Disponible"),
                    ("limitada", "Poca disponibilidad"),
                    ("agotada", "Agotado"),
                ],
                default="disponible",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="materialplanta",
            name="disponibilidad_actualizada_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="materialplanta",
            name="disponibilidad_actualizada_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="api.user",
            ),
        ),
        migrations.AddField(
            model_name="materialplanta",
            name="disponibilidad_nota",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="ordensuministro",
            name="canales_notificacion",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="ordensuministro",
            name="notificada_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="api.user",
            ),
        ),
        migrations.AddField(
            model_name="ordensuministro",
            name="obra",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="ordensuministro",
            name="token_publico",
            # Primero sin unique ni default: con default, todas las filas
            # existentes recibirían el mismo token. Se llena abajo.
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="pago",
            name="fecha_pago",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pago",
            name="notas",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pago",
            name="referencia",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pago",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("transferencia", "Transferencia / consignación"),
                    ("orden_compra", "Orden de compra del cliente"),
                ],
                default="transferencia",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="planta",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="planta",
            name="nota_actualizada_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="planta",
            name="nota_disponibilidad",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="planta",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="permisos",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="plantas",
            field=models.ManyToManyField(
                blank=True, related_name="usuarios", to="api.planta"
            ),
        ),
        migrations.AlterField(
            model_name="pago",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente de revisión"),
                    ("por_confirmar", "Orden de compra por confirmar"),
                    ("aprobado", "Aprobado"),
                    ("rechazado", "Rechazado"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OrdenSuministroItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "cotizacion_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes_items",
                        to="api.cotizacionitem",
                    ),
                ),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.ordensuministro",
                    ),
                ),
            ],
            options={
                "db_table": "orden_suministro_items",
            },
        ),
        migrations.RunPython(permisos_desde_rol, migrations.RunPython.noop),
        migrations.RunPython(tokens_y_items_de_ordenes, migrations.RunPython.noop),
    ]
