# Generated by Django 5.1.4 on 2026-09-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_token_publico_unico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="tipo_precio",
            field=models.CharField(
                choices=[("especial", "Venta especial"), ("detal", "Venta detal")],
                default="especial",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="tipo_precio",
            field=models.CharField(
                choices=[("especial", "Venta especial"), ("detal", "Venta detal")],
                default="especial",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cotizacionitem",
            name="origen_precio",
            field=models.CharField(
                choices=[
                    ("especial", "Venta especial"),
                    ("detal", "Venta detal"),
                    ("manual", "Precio escrito a mano"),
                ],
                default="especial",
                max_length=20,
            ),
        ),
    ]
