# Generated by Django 5.1.4 on 2026-10-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="despacho",
            name="conductor_cedula",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="despacho",
            name="conductor_nombre",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="despacho",
            name="despachado_por_cargo",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="despacho",
            name="despachado_por_nombre",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="despacho",
            name="hora_despacho",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="despacho",
            name="recibido_cargo",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="despacho",
            name="temperatura_despacho",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="material",
            name="codigo",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
